# Linear Regression

In [1]:
from sklearn.linear_model import LinearRegression as LR
from sklearn import datasets

In [2]:
boston = datasets.load_boston()
features = boston.data
target = boston.target
regression = LR()
model = regression.fit(features, target)

In [3]:
model.intercept_

36.45948838509001

In [4]:
model.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [5]:
target[0]*1000

24000.0

In [6]:
round(model.predict(features)[0]*1000, 2)

30003.84

In [7]:
model.coef_[0]*1000

-108.01135783679459

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
features = boston.data[:,0:2]

In [10]:
interaction = PolynomialFeatures(degree=3, include_bias=False, interaction_only=True)
features_interaction = interaction.fit_transform(features)

In [11]:
regression = LR()
model = regression.fit(features_interaction, target)

In [12]:
features[0]

array([6.32e-03, 1.80e+01])

In [13]:
import numpy as np

In [14]:
interaction_term = np.multiply(features[:, 0], features[:, 1])
interaction_term[0]

0.11376

In [15]:
features_interaction[0]

array([6.3200e-03, 1.8000e+01, 1.1376e-01])

In [16]:
features = boston.data[:,0:1]

In [17]:
polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

In [18]:
regression = LR()
model = regression.fit(features_polynomial, target)

In [19]:
features[0]

array([0.00632])

In [20]:
features[0]**2  # polynom x^2

array([3.99424e-05])

In [21]:
features[0]**3  # polynom x^3

array([2.52435968e-07])

In [22]:
features_polynomial[0]  # includes polynomial features of degree param of LR object

array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge

In [24]:
features = boston.data
target = boston.target

In [25]:
scaler = StandardScaler()
features_standardizer = scaler.fit_transform(features)
regression = Ridge(alpha=0.5)
model = regression.fit(features_standardizer, target)