# Neural networks

In [1]:
import warnings
warnings.filterwarnings("ignore")

### Data preprocessing

In [2]:
from sklearn import preprocessing
import numpy as np

In [3]:
features = np.array([[-100.1, 3240.10],
                     [-200.2, -234.1],
                     [5000.5, 150.1],
                     [6000.6, -125.1],
                     [9000.9, -673.1]])

In [4]:
scaler = preprocessing.StandardScaler()
features_standardized = scaler.fit_transform(features)

In [5]:
features_standardized

array([[-1.12541308,  1.96429418],
       [-1.15329466, -0.50068741],
       [ 0.29529406, -0.22809346],
       [ 0.57385917, -0.42335076],
       [ 1.40955451, -0.81216255]])

In [6]:
print("Average:", round(features_standardized[:, 0].mean()))
print("Std:", round(features_standardized[:, 0].std()))

Average: 0
Std: 1


### Neural Network design

In [7]:
from keras import models
from keras import layers

In [8]:
network = models.Sequential()
network.add(layers.Dense(units=16, activation="relu", input_shape=(10,)))
network.add(layers.Dense(units=16, activation="relu"))
network.add(layers.Dense(units=1, activation="sigmoid"))
# 2 layers neural network for classification (1 output layer with sigmoid activator)

In [9]:
network.compile(
    loss="binary_crossentropy", optimizer="rmsprop", metrics=["accuracy"])

### Binary classificator training

In [10]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer

In [11]:
np.random.seed(0)

In [12]:
number_of_features = 1000

In [13]:
(data_train, target_train), (data_test, target_test), = imdb.load_data(num_words=number_of_features)
tokenizer = Tokenizer(num_words=number_of_features)
features_train = tokenizer.sequences_to_matrix(data_train, mode="binary")
features_test = tokenizer.sequences_to_matrix(data_test, mode="binary")

In [14]:
network = models.Sequential()
network.add(layers.Dense(units=16, activation="relu", input_shape=(number_of_features,)))
network.add(layers.Dense(units=16, activation="relu"))
network.add(layers.Dense(units=1, activation="sigmoid"))

In [15]:
network.compile(
    loss="binary_crossentropy", optimizer="rmsprop", metrics=["accuracy"])

In [16]:
history = network.fit(
    features_train,
    target_train,
    epochs=3,
    verbose=1,
    batch_size=100,
    validation_data=(features_test, target_test))

Epoch 1/3
250/250 [==============================] - 2s 5ms/step - loss: 0.5200 - accuracy: 0.7434 - val_loss: 0.3362 - val_accuracy: 0.8568
Epoch 2/3
250/250 [==============================] - 1s 2ms/step - loss: 0.3222 - accuracy: 0.8661 - val_loss: 0.3323 - val_accuracy: 0.8580
Epoch 3/3
250/250 [==============================] - 1s 2ms/step - loss: 0.3100 - accuracy: 0.8721 - val_loss: 0.3379 - val_accuracy: 0.8538


In [17]:
features_train.shape

(25000, 1000)

### Multiclass classificator training

In [18]:
from keras.datasets import reuters
from keras.utils.np_utils import to_categorical

In [19]:
np.random.seed(0)

In [20]:
number_of_features = 5000

In [21]:
data = reuters.load_data(num_words=number_of_features)
(data_train, target_vector_train), (data_test, target_vector_test) = data

In [22]:
tokenizer = Tokenizer(num_words=number_of_features)
features_train = tokenizer.sequences_to_matrix(data_train, mode="binary")
features_test = tokenizer.sequences_to_matrix(data_test, mode="binary")
target_train = to_categorical(target_vector_train)
target_test = to_categorical(target_vector_test)

In [23]:
network = models.Sequential()
network.add(layers.Dense(units=100, activation="relu", input_shape=(number_of_features,)))
network.add(layers.Dense(units=100, activation="relu"))
network.add(layers.Dense(units=46, activation="softmax"))

In [24]:
network.compile(
    loss="categorical_crossentropy",
    optimizer="rmsprop",
    metrics=["accuracy"])

In [25]:
history = network.fit(
    features_train,
    target_train,
    epochs=3,
    verbose=1,
    batch_size=100,
    validation_data=(features_test, target_test))

Epoch 1/3
90/90 [==============================] - 2s 12ms/step - loss: 2.0733 - accuracy: 0.5657 - val_loss: 1.1430 - val_accuracy: 0.7364
Epoch 2/3
90/90 [==============================] - 1s 8ms/step - loss: 0.8130 - accuracy: 0.8216 - val_loss: 0.9317 - val_accuracy: 0.7778
Epoch 3/3
90/90 [==============================] - 1s 8ms/step - loss: 0.5125 - accuracy: 0.8899 - val_loss: 0.9036 - val_accuracy: 0.7974


In [26]:
target_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### Regressor training

In [27]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [28]:
np.random.seed(0)

In [29]:
features, target = make_regression(n_samples=10_000,
                                   n_features=3,
                                   n_informative=3,
                                   n_targets=1,
                                   noise=0.0,
                                   random_state=0)

In [30]:
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.33, random_state=0)

In [31]:
network = models.Sequential()
network.add(layers.Dense(units=32, activation="relu", input_shape=(features_train.shape[1],)))
network.add(layers.Dense(units=32, activation="relu"))
network.add(layers.Dense(units=1))

In [32]:
network.compile(
    loss="mse",
    optimizer="RMSprop",
    metrics=["mse"])

In [33]:
history = network.fit(features_train, target_train, epochs=10, verbose=1, batch_size=100, validation_data=(features_test, target_test))

Epoch 1/10
67/67 [==============================] - 1s 4ms/step - loss: 17368.7622 - mse: 17368.7622 - val_loss: 17342.7227 - val_mse: 17342.7227
Epoch 2/10
67/67 [==============================] - 0s 2ms/step - loss: 15855.3021 - mse: 15855.3021 - val_loss: 15692.0156 - val_mse: 15692.0156
Epoch 3/10
67/67 [==============================] - 0s 2ms/step - loss: 14865.1638 - mse: 14865.1638 - val_loss: 13179.5039 - val_mse: 13179.5039
Epoch 4/10
67/67 [==============================] - 0s 2ms/step - loss: 11855.7776 - mse: 11855.7776 - val_loss: 10019.9834 - val_mse: 10019.9834
Epoch 5/10
67/67 [==============================] - 0s 2ms/step - loss: 8777.1634 - mse: 8777.1634 - val_loss: 6740.7271 - val_mse: 6740.7271
Epoch 6/10
67/67 [==============================] - 0s 2ms/step - loss: 5734.7753 - mse: 5734.7753 - val_loss: 4156.2280 - val_mse: 4156.2275
Epoch 7/10
67/67 [==============================] - 0s 2ms/step - loss: 3539.7690 - mse: 3539.7690 - val_loss: 2330.8333 - val_mse: 

### Predictions

In [34]:
np.random.seed(0)

In [35]:
number_of_features = 10_000

In [36]:
(data_train, target_train), (data_test, target_test) = imdb.load_data(num_words=number_of_features)

In [37]:
tokenizer = Tokenizer(num_words=number_of_features)
features_train = tokenizer.sequences_to_matrix(data_train, mode="binary")
features_test = tokenizer.sequences_to_matrix(data_test, mode="binary")

In [38]:
network = models.Sequential()
network.add(layers.Dense(units=16, activation="relu", input_shape=(number_of_features,)))
network.add(layers.Dense(units=16, activation="relu"))
network.add(layers.Dense(units=1, activation="sigmoid"))

In [39]:
network.compile(
    loss="binary_crossentropy",
    optimizer="rmsprop",
    metrics=["accuracy"])

In [40]:
history = network.fit(features_train, target_train, epochs=3, verbose=1, batch_size=100, validation_data=(features_test, target_test))

Epoch 1/3
250/250 [==============================] - 25s 98ms/step - loss: 0.4486 - accuracy: 0.8027 - val_loss: 0.2832 - val_accuracy: 0.8860
Epoch 2/3
250/250 [==============================] - 2s 6ms/step - loss: 0.2015 - accuracy: 0.9233 - val_loss: 0.2948 - val_accuracy: 0.8835
Epoch 3/3
250/250 [==============================] - 1s 6ms/step - loss: 0.1557 - accuracy: 0.9427 - val_loss: 0.3430 - val_accuracy: 0.8713


In [41]:
predicted_target = network.predict(features_test)

In [42]:
predicted_target[0]

array([0.0953199], dtype=float32)