In [1]:
import numpy as np
from scipy import sparse

In [2]:
vector_row = np.array([1, 2, 3])  # horizontal vector

In [3]:
vector_colum = np.array([[1],
                         [2],
                         [3]])  # vetical vector

In [4]:
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])  # matrix

In [5]:
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

In [6]:
matrix_sparse = sparse.csr_matrix(matrix)  # CSR-matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [7]:
print(vector_row[1])  # select from vector
print(matrix[1][1])  # select from matrix

2
1


In [8]:
matrix = np.arange(1, 13).reshape(3,4)  # matrix generation from arange
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
matrix.shape  # shape of matrix (rows, columns)

(3, 4)

In [10]:
matrix.size  # quantity of elements of the matrix

12

In [11]:
matrix.ndim  # matrix dimensions

2

In [12]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
add_100 = lambda i: i + 100
vectorized_add_100 = np.vectorize(add_100)  # vectorized lambda function
print(vectorized_add_100(matrix))

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [14]:
np.max(matrix)

9

In [15]:
np.min(matrix)

1

In [16]:
np.mean(matrix)

5.0

In [17]:
np.var(matrix)  # dispersion

6.666666666666667

In [18]:
np.std(matrix)  # standard deviation

2.581988897471611

In [19]:
matrix = np.arange(1, 13).reshape(4, 3)
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [21]:
matrix.T  # transpose of the matrix (shift indexes of rows and columns)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [22]:
matrix.flatten()  # reshape matrix to vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
np.linalg.det(matrix)  # determinant of the matrix

0.0

In [24]:
matrix.diagonal()

array([1, 4, 9])

In [25]:
matrix.trace()  # sum of the elements of the main diagonal

14

In [26]:
matrix = np.array([[1, -1, 3],
                   [1,  1, 6],
                   [3,  8, 9]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print()
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]

[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [27]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
np.dot(vector_a, vector_b)  # scalar product of the vectors

32

In [28]:
# np.add(_matrix1_, _matrix2_) - addition
# np.subtract(_matrix1_, _matrix2_) - subtraction
# np.dot(_matrix1_, _matrix2_) - product

In [29]:
np.random.seed(0)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])