In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
feature = np.array([[-500.5],
                    [-100.1],
                    [0],
                    [100.1],
                    [900.9]])

In [3]:
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))  # scaler creation
scaled_feature = minmax_scale.fit_transform(feature)  # scale the feature
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [4]:
x = np.array([[-1000.1],
              [-200.2],
              [500.5],
              [600.6],
              [9000.9]])

In [5]:
scaler = preprocessing.StandardScaler()  # transform the feature to [avg = 0, sd = 1]
standardized = scaler.fit_transform(x)
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [6]:
print("Mean:", round(standardized.mean()))
print("Standart Deviaton:", standardized.std())

Mean: 0.0
Standart Deviaton: 1.0


In [7]:
features = np.array([[0.5, 0.5],
                     [1.1, 3.4],
                     [1.5, 20.2],
                     [1.63, 34.4],
                     [10.9, 3.3]])

In [8]:
normalizer = preprocessing.Normalizer()  # scale the feature to get the unit rate
normalizer.transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [9]:
features = np.array([[2, 3],
                     [2, 3],
                     [2, 3]])

In [10]:
polynomial_interaction = preprocessing.PolynomialFeatures(degree=2, include_bias=False)
polynomial_interaction.fit_transform(features)  # create the polinomial and interaction features

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [11]:
interaction = preprocessing.PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
interaction.fit_transform(features)  # interaction features only

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])