# Naive Bayes

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
iris = datasets.load_iris()
features = iris.data
target = iris.target
classifier = GaussianNB()
model = classifier.fit(features, target)

In [3]:
new_observation = [[4, 4, 4, 0.4]]
model.predict(new_observation)

array([1])

In [4]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
text_data = np.array(["Brazil - my love. Brazil!",
                      "Brazil is better",
                      "Germany beats both"])
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

In [6]:
features = bag_of_words.toarray()
target = ([0, 0, 1])

In [7]:
classifier = MultinomialNB(class_prior=[0.25, 0.5])
model = classifier.fit(features, target)

In [8]:
new_observation = [[0, 0, 0, 1, 0, 1, 0, 0]]
model.predict(new_observation)

array([0])

In [9]:
from shttp://localhost:8888/notebooks/Chapter_18.ipynb#Naive-Bayesklearn.naive_bayes import BernoulliNB

In [10]:
features = np.random.randint(2, size=(100, 3))
target = np.random.randint(2, size=(100, 1)).ravel()

In [11]:
classifier = BernoulliNB(class_prior=[0.25, 0.5])
model = classifier.fit(features, target)

In [12]:
from sklearn.calibration import CalibratedClassifierCV

In [13]:
features = iris.data
target = iris.target
classifier = GaussianNB()
classifier_sigmoid = CalibratedClassifierCV(classifier, cv=2, method="sigmoid")
classifier_sigmoid.fit(features, target)

CalibratedClassifierCV(base_estimator=GaussianNB(), cv=2)

In [14]:
new_observation = [[2.6, 2.6, 2.6, 0.4]]
classifier_sigmoid.predict_proba(new_observation)

array([[0.31859969, 0.63663466, 0.04476565]])

In [15]:
classifier.fit(features, target).predict_proba(new_observation)

array([[2.31548432e-04, 9.99768128e-01, 3.23532277e-07]])